/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParaAgenciasIndexRouteImport } from './routes/para-agencias/index'
import { Route as ContatoIndexRouteImport } from './routes/contato/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppPainelRouteImport } from './routes/app.painel'
import { Route as AppMapaRouteImport } from './routes/app.mapa'
import { Route as AppKanbanRouteImport } from './routes/app.kanban'
import { Route as AppHojeRouteImport } from './routes/app.hoje'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app.configuracoes.index'
import { Route as AppConfiguracoesPlanoRouteImport } from './routes/app.configuracoes.plano'
import { Route as AppConfiguracoesMotorRouteImport } from './routes/app.configuracoes.motor'
import { Route as AppConfiguracoesIntegracoesRouteImport } from './routes/app.configuracoes.integracoes'
import { Route as AppConfiguracoesDadosRouteImport } from './routes/app.configuracoes.dados'
import { Route as AppConfiguracoesContaRouteImport } from './routes/app.configuracoes.conta'

const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaAgenciasIndexRoute = ParaAgenciasIndexRouteImport.update({
  id: '/para-agencias/',
  path: '/para-agencias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoIndexRoute = ContatoIndexRouteImport.update({
  id: '/contato/',
  path: '/contato/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppHojeRoute = AppHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesPlanoRoute = AppConfiguracoesPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesMotorRoute = AppConfiguracoesMotorRouteImport.update({
  id: '/motor',
  path: '/motor',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesIntegracoesRoute =
  AppConfiguracoesIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesDadosRoute = AppConfiguracoesDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesContaRoute = AppConfiguracoesContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/historico': typeof AppHistoricoRoute
  '/app/hoje': typeof AppHojeRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/painel': typeof AppPainelRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/contato/': typeof ContatoIndexRoute
  '/para-agencias/': typeof ParaAgenciasIndexRoute
  '/app/configuracoes/conta': typeof AppConfiguracoesContaRoute
  '/app/configuracoes/dados': typeof AppConfiguracoesDadosRoute
  '/app/configuracoes/integracoes': typeof AppConfiguracoesIntegracoesRoute
  '/app/configuracoes/motor': typeof AppConfiguracoesMotorRoute
  '/app/configuracoes/plano': typeof AppConfiguracoesPlanoRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/hoje': typeof AppHojeRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/painel': typeof AppPainelRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/contato': typeof ContatoIndexRoute
  '/para-agencias': typeof ParaAgenciasIndexRoute
  '/app/configuracoes/conta': typeof AppConfiguracoesContaRoute
  '/app/configuracoes/dados': typeof AppConfiguracoesDadosRoute
  '/app/configuracoes/integracoes': typeof AppConfiguracoesIntegracoesRoute
  '/app/configuracoes/motor': typeof AppConfiguracoesMotorRoute
  '/app/configuracoes/plano': typeof AppConfiguracoesPlanoRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/historico': typeof AppHistoricoRoute
  '/app/hoje': typeof AppHojeRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/painel': typeof AppPainelRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/contato/': typeof ContatoIndexRoute
  '/para-agencias/': typeof ParaAgenciasIndexRoute
  '/app/configuracoes/conta': typeof AppConfiguracoesContaRoute
  '/app/configuracoes/dados': typeof AppConfiguracoesDadosRoute
  '/app/configuracoes/integracoes': typeof AppConfiguracoesIntegracoesRoute
  '/app/configuracoes/motor': typeof AppConfiguracoesMotorRoute
  '/app/configuracoes/plano': typeof AppConfiguracoesPlanoRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/precos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/verificar-email'
    | '/app/admin'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/hoje'
    | '/app/kanban'
    | '/app/mapa'
    | '/app/painel'
    | '/auth/callback'
    | '/app/'
    | '/contato/'
    | '/para-agencias/'
    | '/app/configuracoes/conta'
    | '/app/configuracoes/dados'
    | '/app/configuracoes/integracoes'
    | '/app/configuracoes/motor'
    | '/app/configuracoes/plano'
    | '/app/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/precos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/verificar-email'
    | '/app/admin'
    | '/app/agenda'
    | '/app/historico'
    | '/app/hoje'
    | '/app/kanban'
    | '/app/mapa'
    | '/app/painel'
    | '/auth/callback'
    | '/app'
    | '/contato'
    | '/para-agencias'
    | '/app/configuracoes/conta'
    | '/app/configuracoes/dados'
    | '/app/configuracoes/integracoes'
    | '/app/configuracoes/motor'
    | '/app/configuracoes/plano'
    | '/app/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/precos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/verificar-email'
    | '/app/admin'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/historico'
    | '/app/hoje'
    | '/app/kanban'
    | '/app/mapa'
    | '/app/painel'
    | '/auth/callback'
    | '/app/'
    | '/contato/'
    | '/para-agencias/'
    | '/app/configuracoes/conta'
    | '/app/configuracoes/dados'
    | '/app/configuracoes/integracoes'
    | '/app/configuracoes/motor'
    | '/app/configuracoes/plano'
    | '/app/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ContatoIndexRoute: typeof ContatoIndexRoute
  ParaAgenciasIndexRoute: typeof ParaAgenciasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-agencias/': {
      id: '/para-agencias/'
      path: '/para-agencias'
      fullPath: '/para-agencias/'
      preLoaderRoute: typeof ParaAgenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato/': {
      id: '/contato/'
      path: '/contato'
      fullPath: '/contato/'
      preLoaderRoute: typeof ContatoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/painel': {
      id: '/app/painel'
      path: '/painel'
      fullPath: '/app/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hoje': {
      id: '/app/hoje'
      path: '/hoje'
      fullPath: '/app/hoje'
      preLoaderRoute: typeof AppHojeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/plano': {
      id: '/app/configuracoes/plano'
      path: '/plano'
      fullPath: '/app/configuracoes/plano'
      preLoaderRoute: typeof AppConfiguracoesPlanoRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/motor': {
      id: '/app/configuracoes/motor'
      path: '/motor'
      fullPath: '/app/configuracoes/motor'
      preLoaderRoute: typeof AppConfiguracoesMotorRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/integracoes': {
      id: '/app/configuracoes/integracoes'
      path: '/integracoes'
      fullPath: '/app/configuracoes/integracoes'
      preLoaderRoute: typeof AppConfiguracoesIntegracoesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/dados': {
      id: '/app/configuracoes/dados'
      path: '/dados'
      fullPath: '/app/configuracoes/dados'
      preLoaderRoute: typeof AppConfiguracoesDadosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/conta': {
      id: '/app/configuracoes/conta'
      path: '/conta'
      fullPath: '/app/configuracoes/conta'
      preLoaderRoute: typeof AppConfiguracoesContaRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesContaRoute: typeof AppConfiguracoesContaRoute
  AppConfiguracoesDadosRoute: typeof AppConfiguracoesDadosRoute
  AppConfiguracoesIntegracoesRoute: typeof AppConfiguracoesIntegracoesRoute
  AppConfiguracoesMotorRoute: typeof AppConfiguracoesMotorRoute
  AppConfiguracoesPlanoRoute: typeof AppConfiguracoesPlanoRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesContaRoute: AppConfiguracoesContaRoute,
  AppConfiguracoesDadosRoute: AppConfiguracoesDadosRoute,
  AppConfiguracoesIntegracoesRoute: AppConfiguracoesIntegracoesRoute,
  AppConfiguracoesMotorRoute: AppConfiguracoesMotorRoute,
  AppConfiguracoesPlanoRoute: AppConfiguracoesPlanoRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppHojeRoute: typeof AppHojeRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppMapaRoute: typeof AppMapaRoute
  AppPainelRoute: typeof AppPainelRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppHistoricoRoute: AppHistoricoRoute,
  AppHojeRoute: AppHojeRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppMapaRoute: AppMapaRoute,
  AppPainelRoute: AppPainelRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ContatoIndexRoute: ContatoIndexRoute,
  ParaAgenciasIndexRoute: ParaAgenciasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
