import {
  // Navegação
  Map,
  Columns3,
  BarChart3,
  Target,
  CalendarDays,
  Sunrise,
  Activity,
  MessageSquareText,
  History,
  ShieldCheck,
  Settings,
  // Ações
  Plus,
  Minus,
  Pencil,
  Trash2,
  X,
  Check,
  Search,
  SlidersHorizontal,
  ListFilter,
  RefreshCcw,
  RotateCcw,
  Download,
  Upload,
  Copy,
  ExternalLink,
  Ellipsis,
  EllipsisVertical,
  Send,
  Archive,
  Lock,
  Eye,
  EyeOff,
  Ban,
  PlusCircle,
  MinusCircle,
  Save,
  Share2,
  PlayCircle,
  Menu,
  SkipForward,
  // Lead
  Building2,
  MapPin,
  Navigation,
  Star,
  Flame,
  Thermometer,
  Snowflake,
  CircleDot,
  Sparkles,
  Phone,
  Mail,
  Globe2,
  Zap,
  CircleDollarSign,
  User,
  Users,
  Tags,
  Pin,
  PinOff,
  Clock,
  GitBranch,
  TrendingUp,
  Instagram,
  GlobeLock,
  Lightbulb,
  PhoneCall,
  MessageSquare,
  Megaphone,
  Trophy,
  CalendarCheck,
  Cpu,
  Locate,
  // Feedback
  CheckCircle2,
  AlertCircle,
  XCircle,
  Info,
  CircleHelp,
  LoaderCircle,
  TriangleAlert,
  // Layout
  List,
  LayoutDashboard,
  PanelLeftClose,
  PanelLeftOpen,
  Maximize2,
  Minimize2,
  // Chevrons / setas
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  ArrowDownRight,
  // Pipeline
  Circle,
  BadgeCheck,
  MessageCircle,
  CircleCheckBig,
  CircleX,
  GripVertical,
  // Agenda
  CalendarPlus,
  CalendarClock,
  ClockAlert,
  UsersRound,
  Flag,
  // Marca / utilitários
  Moon,
  Sun,
  StickyNote,
  Bell,
  Bookmark,
  Wifi,
  WifiOff,
  // Mensagens
  FileText,
  Braces,
  Smile,
  Bold,
  Italic,
  Strikethrough,
  Code2,
  List as ListIcon,
  ListOrdered,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Registro central de ícones do Radar Local.
 *
 * Cada domínio agrupa os ícones por função. Componentes devem consumir este
 * registro em vez de importar ícones diretamente. Isso garante que o mesmo
 * conceito use o mesmo ícone em todo o produto.
 */
export const icons = {
  /** Navegação principal — sidebar, rail, mobile, command palette */
  navigation: {
    map: Map,
    pipeline: Columns3,
    opportunities: Target,
    today: Sunrise,
    activities: Activity,
    analytics: BarChart3,
    messages: MessageSquareText,
    history: History,
    administration: ShieldCheck,
    settings: Settings,
  },

  /** Ações genéricas — CRUD, busca, navegação, utilidades */
  actions: {
    add: Plus,
    remove: Minus,
    edit: Pencil,
    delete: Trash2,
    close: X,
    confirm: Check,
    search: Search,
    filter: SlidersHorizontal,
    filterList: ListFilter,
    refresh: RefreshCcw,
    reset: RotateCcw,
    download: Download,
    upload: Upload,
    copy: Copy,
    openExternal: ExternalLink,
    more: Ellipsis,
    send: Send,
    archive: Archive,
    lock: Lock,
    view: Eye,
    hide: EyeOff,
    ban: Ban,
    addCircle: PlusCircle,
    removeCircle: MinusCircle,
    save: Save,
    share: Share2,
    play: PlayCircle,
    menu: Menu,
    skipForward: SkipForward,
    moreVertical: EllipsisVertical,
  },

  /** Leads e empresas */
  lead: {
    company: Building2,
    category: Tags,
    location: MapPin,
    distance: Navigation,
    rating: Star,
    score: Target,
    hot: Flame,
    warm: Thermometer,
    cold: Snowflake,
    opportunity: Sparkles,
    phone: Phone,
    email: Mail,
    website: Globe2,
    nextAction: Zap,
    value: CircleDollarSign,
    assignedUser: User,
    team: Users,
    pin: Pin,
    unpin: PinOff,
    clock: Clock,
    branch: GitBranch,
    trendingUp: TrendingUp,
    instagram: Instagram,
    messageCircle: MessageCircle,
    globeLock: GlobeLock,
    lightbulb: Lightbulb,
    phoneCall: PhoneCall,
    messageSquare: MessageSquare,
    megaphone: Megaphone,
    trophy: Trophy,
  },

  /** Feedback e estados do sistema */
  feedback: {
    success: CheckCircle2,
    warning: TriangleAlert,
    danger: XCircle,
    info: Info,
    help: CircleHelp,
    loading: LoaderCircle,
    attention: AlertCircle,
  },

  /** Layout e visualizações */
  layout: {
    list: List,
    board: Columns3,
    dashboard: LayoutDashboard,
    collapseSidebar: PanelLeftClose,
    expandSidebar: PanelLeftOpen,
    maximize: Maximize2,
    minimize: Minimize2,
  },

  /** Chevrons e setas direcionais */
  directional: {
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    sort: ArrowUpDown,
    growth: ArrowUpRight,
    decline: ArrowDownRight,
  },

  /** Pipeline / Kanban */
  pipeline: {
    circle: Circle,
    qualified: BadgeCheck,
    contacted: MessageCircle,
    won: CircleCheckBig,
    discarded: CircleX,
    drag: GripVertical,
  },

  /** Agenda e atividades */
  agenda: {
    calendar: CalendarDays,
    createActivity: CalendarPlus,
    reschedule: CalendarClock,
    overdue: ClockAlert,
    meeting: UsersRound,
    priority: Flag,
    completed: CalendarCheck,
  },

  /** Mensagens e templates */
  messages: {
    template: FileText,
    variables: Braces,
    emoji: Smile,
    bold: Bold,
    italic: Italic,
    strikethrough: Strikethrough,
    code: Code2,
    bulletList: ListIcon,
    orderedList: ListOrdered,
    insights: Sparkles,
  },

  /** Tema */
  theme: {
    light: Sun,
    dark: Moon,
  },

  /** Sistema (não categorizados acima) */
  system: {
    note: StickyNote,
    notification: Bell,
    bookmark: Bookmark,
    online: Wifi,
    offline: WifiOff,
    cpu: Cpu,
    locate: Locate,
  },
} as const satisfies Record<string, Record<string, LucideIcon>>;

/** Extrai o tipo de um ícone do registro a partir do caminho dotted. */
export type IconPath = {
  [K in keyof typeof icons]: `${K}.${keyof (typeof icons)[K] & string}`;
}[keyof typeof icons];
