import { useEffect, useRef, useState } from "react";
import { Copy, MessageCircle, Sparkles, Loader2 } from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useMessageStore, useSettingsStore } from "@/stores";
import { buildContactMessage } from "@/lib/message-fill";
import { whatsappDisplay } from "@/lib/whatsapp";
import { useOutbound } from "@/hooks/useOutbound";
import { generateContactMessage } from "@/lib/ai-message";
import type { Lead } from "@/types";

/**
 * Per-lead message composer — the single-target counterpart of
 * `BulkMessageDialog`. Same template resolution (`buildContactMessage`) and the
 * same outbound gate (`useOutbound`), so opt-out/landline rules still apply.
 */
export function PrepareMessageDialog({
  lead,
  open,
  onOpenChange,
  materialize,
  autoGenerate = false,
}: {
  lead: Lead;
  open: boolean;
  onOpenChange: (v: boolean) => void;
  /** Set when the target is a discovery result not yet in the funnel. */
  materialize?: { searchId: string; placeId: string };
  /** Trigger AI generation once, automatically, the first time the dialog
   * opens — used by NbaCard's first-contact CTA so the user reviews an
   * AI-written opener instead of the raw template. */
  autoGenerate?: boolean;
}) {
  const template = useMessageStore((s) => s.template);
  const senderName = useSettingsStore((s) => s.senderName);
  const userName = useSettingsStore((s) => s.userName);
  const companyName = useSettingsStore((s) => s.companyName);
  const signature = useSettingsStore((s) => s.signature);
  const { openWhatsApp } = useOutbound();
  const [draft, setDraft] = useState("");
  const [aiLoading, setAiLoading] = useState(false);
  const autoGeneratedRef = useRef(false);

  async function handleGenerateAi() {
    setAiLoading(true);
    const result = await generateContactMessage(lead.id);
    setAiLoading(false);
    if (result.ok) {
      setDraft(result.message);
    } else if (result.reason === "insufficient_signal") {
      toast("Sinal insuficiente para IA — mantendo o modelo padrão.");
    } else {
      toast.error("Não foi possível gerar com IA agora — mantendo o modelo padrão.");
    }
  }

  // Reset to the freshly rendered template each time the dialog is opened —
  // editing is scoped to one send, not persisted as the lead's message.
  useEffect(() => {
    if (!open) {
      autoGeneratedRef.current = false;
      return;
    }
    setDraft(buildContactMessage(template, lead, { senderName, userName, companyName, signature }));
  }, [open, template, lead, senderName, userName, companyName, signature]);

  // Auto-trigger AI generation once per open (not on every dep change above).
  useEffect(() => {
    if (open && autoGenerate && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      handleGenerateAi();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, autoGenerate]);

  const wa = whatsappDisplay(lead.whatsapp, lead.phone);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Preparar mensagem</DialogTitle>
          <DialogDescription>Revise antes de enviar — o envio não é automático.</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <div>
            <p className="text-sm font-semibold">{lead.companyName}</p>
            <p className="text-xs text-muted-foreground">
              {wa ? wa.value : (lead.phone ?? "sem contato")}
            </p>
          </div>
          <Textarea rows={8} value={draft} onChange={(e) => setDraft(e.target.value)} />
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span className="tabular-nums">{draft.length} caracteres</span>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                disabled={aiLoading}
                onClick={handleGenerateAi}
                title="Gerar abertura específica a partir do sinal do lead (site/nota/avaliações)"
              >
                {aiLoading ? (
                  <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Sparkles className="mr-1 h-3.5 w-3.5" />
                )}
                {aiLoading ? "Gerando..." : "Gerar com IA"}
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  navigator.clipboard.writeText(draft);
                  toast.success("Copiado");
                }}
              >
                <Copy className="mr-1 h-3.5 w-3.5" />
                Copiar
              </Button>
              <Button
                size="sm"
                onClick={async () => {
                  const sent = await openWhatsApp(lead, { message: draft, materialize });
                  if (sent) onOpenChange(false);
                }}
              >
                <MessageCircle className="mr-1 h-3.5 w-3.5" />
                Abrir WhatsApp
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
