import { useEffect, useRef, useState } from "react";
import { Copy, MessageCircle, Sparkles, Loader2, UserRound } from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  SheetDialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useMessageStore, useSettingsStore } from "@/stores";
import { buildContactMessage } from "@/lib/message-fill";
import { whatsappDisplay } from "@/lib/whatsapp";
import { useOutbound } from "@/hooks/useOutbound";
import { generateContactMessage } from "@/lib/ai-message";
import type { DisplayLead, Lead } from "@/types";
import { track } from "@/lib/analytics";
import { useActivationStore } from "@/stores/activation";

/**
 * Per-lead message composer — the single-target counterpart of
 * `BulkMessageDialog`. Same template resolution (`buildContactMessage`) and the
 * same outbound gate (`useOutbound`), so opt-out/landline rules still apply.
 */
export function PrepareMessageDialog({
  lead,
  open,
  onOpenChange,
  materialize,
  autoGenerate = false,
}: {
  lead: DisplayLead;
  open: boolean;
  onOpenChange: (v: boolean) => void;
  /** Set when the target is a discovery result not yet in the funnel. */
  materialize?: { searchId: string; placeId: string };
  /** Trigger AI generation once, automatically, the first time the dialog
   * opens — used by NbaCard's first-contact CTA so the user reviews an
   * AI-written opener instead of the raw template. */
  autoGenerate?: boolean;
}) {
  const template = useMessageStore((s) => s.template);
  const senderName = useSettingsStore((s) => s.senderName);
  const userName = useSettingsStore((s) => s.userName);
  const companyName = useSettingsStore((s) => s.companyName);
  const signature = useSettingsStore((s) => s.signature);
  const updateSettings = useSettingsStore((s) => s.set);
  const { openWhatsApp } = useOutbound();
  const [draft, setDraft] = useState("");
  const [aiLoading, setAiLoading] = useState(false);
  const [profileEditing, setProfileEditing] = useState(false);
  const autoGeneratedRef = useRef(false);
  const markMilestone = useActivationStore((state) => state.mark);

  async function handleGenerateAi() {
    setAiLoading(true);
    const result = await generateContactMessage(lead.id);
    setAiLoading(false);
    if (result.ok) {
      setDraft(result.message);
    } else if (result.reason === "insufficient_signal") {
      toast("Sinal insuficiente para IA — mantendo o modelo padrão.");
    } else {
      toast.error("Não foi possível gerar com IA agora — mantendo o modelo padrão.");
    }
  }

  // Reset to the freshly rendered template each time the dialog is opened —
  // editing is scoped to one send, not persisted as the lead's message.
  useEffect(() => {
    if (!open) {
      autoGeneratedRef.current = false;
      return;
    }
    setProfileEditing(!senderName.trim() || !companyName.trim());
    setDraft(buildContactMessage(template, lead, { senderName, userName, companyName, signature }));
    track("message_prepared", { leadId: lead.id, source: "composer_opened" });
    markMilestone("firstMessagePrepared", { leadId: lead.id });
  }, [open, template, lead, senderName, userName, companyName, signature, markMilestone]);

  // Auto-trigger AI generation once per open (not on every dep change above).
  useEffect(() => {
    if (open && autoGenerate && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      handleGenerateAi();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, autoGenerate]);

  const wa = whatsappDisplay(lead.whatsapp, lead.phone);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <SheetDialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Preparar mensagem</DialogTitle>
          <DialogDescription>Revise antes de enviar — o envio não é automático.</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          {profileEditing && (
            <div className="rounded-xl border border-primary/15 bg-primary-subtle p-3.5">
              <div className="flex items-start gap-2.5">
                <div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-primary-soft text-primary">
                  <UserRound className="h-4 w-4" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium text-foreground">
                    Como você quer se apresentar?
                  </p>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    Usaremos esses dados para personalizar suas mensagens.
                  </p>
                </div>
              </div>
              <div className="mt-3 grid gap-2 sm:grid-cols-2">
                <Input
                  value={senderName}
                  onChange={(event) => updateSettings({ senderName: event.target.value })}
                  placeholder="Seu nome"
                  aria-label="Nome usado nas mensagens"
                  className="h-10 bg-surface"
                />
                <Input
                  value={companyName}
                  onChange={(event) => updateSettings({ companyName: event.target.value })}
                  placeholder="Nome da sua empresa"
                  aria-label="Empresa usada nas mensagens"
                  className="h-10 bg-surface"
                />
              </div>
              <div className="mt-2.5 flex justify-end">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => setProfileEditing(false)}
                  disabled={!senderName.trim()}
                >
                  Aplicar à mensagem
                </Button>
              </div>
            </div>
          )}
          <div>
            <p className="text-sm font-semibold">{lead.companyName}</p>
            <p className="text-xs text-muted-foreground">
              {wa ? wa.value : (lead.phone ?? "sem contato")}
            </p>
          </div>
          <Textarea rows={8} value={draft} onChange={(e) => setDraft(e.target.value)} />
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span className="tabular-nums">{draft.length} caracteres</span>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                disabled={aiLoading}
                onClick={handleGenerateAi}
                title="Gerar abertura específica a partir do sinal do lead (site/nota/avaliações)"
              >
                {aiLoading ? (
                  <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Sparkles className="mr-1 h-3.5 w-3.5" />
                )}
                {aiLoading ? "Gerando..." : "Gerar com IA"}
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  navigator.clipboard.writeText(draft);
                  toast.success("Copiado");
                }}
              >
                <Copy className="mr-1 h-3.5 w-3.5" />
                Copiar
              </Button>
              <Button
                size="sm"
                onClick={async () => {
                  const sent = await openWhatsApp(lead, { message: draft, materialize });
                  if (sent) onOpenChange(false);
                }}
              >
                <MessageCircle className="mr-1 h-3.5 w-3.5" />
                Abrir WhatsApp
              </Button>
            </div>
          </div>
        </div>
      </SheetDialogContent>
    </Dialog>
  );
}
